### ISSUE TITLE
Allow large amounts of location/resource properties and status data to be scrolled.

### ISSUE THREAD

**Issue by iglooa** [IBM/agile-service-manager-gis-map-plugin#10]
Some resources have large amounts of properties and/or status data and these don't currently render nicely when a location is clicked on. It'd be good if the popup could be scaled appropriately and the property and status data made scrollable.

**Comment by Kilian-Collender** [comment]
This is a nice idea, if you have time to contribute a PR with a possible solution, we can look to add that support.

**Comment by Kilian-Collender** [comment]
Project is being archived
