### ISSUE TITLE
Optionally mark links according to the status of locations at either end

### ISSUE THREAD

**Issue by iglooa** [IBM/agile-service-manager-gis-map-plugin#11]
It'd be useful to mark a link according to the highest severity of the locations at each end to help the user identify where there are problems. 

For example, the Waterloo & City line has no service in this image but it's not apparent unless looking at the location status on either end. 

<img width="797" alt="image" src="https://user-images.githubusercontent.com/12982259/87754869-c55bc300-c7fd-11ea-912a-5f82458fcc25.png">

**Comment by Kilian-Collender** [comment]
Sorry for the late reply, there is no plan to add link status marker, as the ASM tool doesn't do this. But feel free to create a PR to add this as a configurable setting.
