### ISSUE TITLE
Add tooltip to relationships and ability to navigate to the location at either end

### ISSUE THREAD

**Issue by iglooa** [IBM/agile-service-manager-gis-map-plugin#12]
It would be useful to know the names and types of resources/locations at the end of a link through a tooltip. It would also be useful to have the ability to navigate to either end of the relationship and focus on it from the tooltip given that they may be geographically far apart and outside of the user's viewport.

**Comment by Kilian-Collender** [comment]
This is a nice idea, if you have time to contribute a PR with a possible solution, we can look to add that support.

**Comment by Kilian-Collender** [comment]
Project is being archived
