### ISSUE TITLE
Add the ability to only render relationships when a location/resource is clicked.

### ISSUE THREAD

**Issue by iglooa** [IBM/agile-service-manager-gis-map-plugin#8]
Some environments have huge numbers of relationships between locations and they make the view unusable. It'd be good to only show relationships when a location is clicked and for the viewport to be updated as needed to capture the related locations/resources.

**Comment by Kilian-Collender** [comment]
This is a nice idea, if you have time to contribute a PR with a possible solution, we can look to add that support.

**Comment by Kilian-Collender** [comment]
Project is being archived
